In [1]:
import pandas as pd 
import numpy as np

In [41]:
df = pd.read_csv("/home/dhankar/_dc_main/_JIRA_All/Ayush_Shaw/ceil_mode.csv")
params = {}
params['single_col'] = 0 
# 0 - Boolean = All Columns 
# 1 - Boolean = Single Column 
params['col_index'] = 3
params['ceil_mode'] = 1 
# 1 - Boolean = CEIL_MODE
# 0 - Boolean = FLOOR_MODE

print(params)

{'single_col': 0, 'col_index': 3, 'ceil_mode': 1}

In [42]:
def ceil_only_data(df,params):
    """
    called within - ceil_floor(df,params):
    """
    print("---CEIL----")
    sn_col = params['single_col']  # 0 - Boolean = Not True
    col_id = params['col_index']   # InT value
    
    sn_col_data = df.iloc[:, col_id]
    
    if sn_col == 1:
        if (np.issubdtype(sn_col_data.dtype, np.number)) :
            print(sn_col)
            print("-------")
            sn_col_data = sn_col_data.apply(np.ceil)
            return df
    else:
        all_cols = df.columns.tolist()
        for i in all_cols:
            if (np.issubdtype(df[i].dtype, np.number)) :
                df[i] = df[i].apply(np.ceil)
        return df

def floor_only_data(df,params):
    """
    called within - ceil_floor(df,params):
    """
    print("---FLOOR----")
    sn_col = params['single_col']  # 0 - Boolean = Not True
    col_id = params['col_index']   # InT value
    
    sn_col_data = df.iloc[:, col_id]
    
    if sn_col == 1:
        if (np.issubdtype(sn_col_data.dtype, np.number)) :
            print(sn_col)
            print("-------")
            sn_col_data = sn_col_data.apply(np.floor)
            return df
    else:
        all_cols = df.columns.tolist()
        for i in all_cols:
            if (np.issubdtype(df[i].dtype, np.number)) :
                df[i] = df[i].apply(np.floor)
        return df

def ceil_floor(df,params):
    ceil_m = params['ceil_mode']   # 0 - Boolean = floor_only_data
    if ceil_m == 1:
        df = ceil_only_data(df,params)
    else:
        df =  floor_only_data(df,params)
    return df    
    
ceil_floor(df,params)

---CEIL----

    HEIGHT  WEIGHT SPECIMEN    Nums
0      6.0    69.0      Man    23.0
1      3.0    34.0      Boy    34.0
2      4.0    46.0     Girl    46.0
3      5.0    63.0     Girl    80.0
4      6.0    88.0      Man   114.0
5      3.0    44.0      Boy   148.0
6      3.0    55.0     Girl   181.0
7      6.0    78.0     Girl   215.0
8      7.0    77.0      Man   249.0
9      4.0    33.0      Boy   283.0
10     4.0    44.0     Girl   317.0
11     6.0    66.0     Girl   394.0
12     7.0    82.0      Man   471.0
13     3.0    25.0      Boy   548.0
14     5.0    33.0     Girl   625.0
15     6.0    54.0     Girl   703.0
16     6.0    75.0      Man   780.0
17     4.0    23.0      Boy   857.0
18     5.0    34.0     Girl   934.0
19     6.0    53.0     Girl  1012.0
20     7.0    69.0      Man  1089.0
21     4.0    33.0      Boy  1166.0
22     5.0    34.0     Girl  1243.0
23     6.0    65.0     Girl  1321.0